### PR TITLE
Fix mux NDF

### PR DESCRIPTION
**Pull request by n8maninger**

### CODE REVIEW

**Review by ChrisSchinnerl — APPROVED** [review]

**Comment by lukechampine** [comment]
Why does this fix the NDF?

**Comment by n8maninger** [comment]
When the client checks the error of `s.Close()`, it sometimes returns `ErrPeerClosedConn` because the server's `defer m.Close()` has already closed the connection, and the stream error has been set. This change keeps the underlying connection open until the test is done.

```
=== RUN   TestMux
      mux_test.go:67: peer closed underlying connection
 --- FAIL: TestMux (0.01s)
```

**Review by ChrisSchinnerl — CHANGES_REQUESTED** [review]
I think it's safe to just ignore the error in `Close` itself. Otherwise the user of the mix in production also runs into this edge case which might be annoying if it's harmless anyway.

**Comment by lukechampine** [comment]
should we cherry-pick 8be569d7fea7a9c5ab0c674b87bf0591ace8ddfc into this branch?

**Comment by ChrisSchinnerl** [comment]
Either that or we could also just merge #17 now that it's passing the tests and rebase this. The comments should be addressed unless you got new ones.

**Comment by ChrisSchinnerl** [comment]
I'm also inclined to say that we should probably not defer the close and ignore the error. If someone used the mux in production and doesn't know the internals it could be confusing to get an error that we missed in our tests.

**Comment by lukechampine** [comment]
A common pattern is to `defer foo.Close()` immediately, but later call `foo.Close()` explicitly and handle the error. This ensures that resources are always cleaned up in the event of an early return, while also handling the close error if everything else succeeds. (And calling `Close` twice should always be ok.) That's my recommendation here as well: we can `defer m.Close()` but we should also call it explicitly at the end of the test and handle the error.

**Comment by n8maninger** [comment]
Alright, cherry-picked Chris's commit from #17 and reverted the change to `t.Cleanup()`. We should be able to just close this and merge #17 if it's ready.

**Comment by n8maninger** [comment]
Alright, reverted the change to `t.Cleanup` cherry-picked Chris' change from #17 and added an explicit call and check to `m.Close()`

**Review by peterjan — APPROVED** [review]

**Pull request merged**
